/** Pure Layer A: invisible Unicode, agent trailers, Generated-with banners. */

export interface LayerARemoved {
  readonly unicode: number
  readonly trailer: number
  readonly banner: number
}

export interface LayerAResult {
  readonly text: string
  readonly removed: LayerARemoved
}

const ZWSP_RE = /[\u200B\u2060\uFEFF]/u
const BIDI_OVERRIDE_RE = /[\u202A-\u202E]/u
const TAG_RE = /[\u{E0001}\u{E0020}-\u{E007E}]/u

const AGENT_TRAILER_RE = new RegExp(
  "^[ \\t]*(?:" +
    "(?:Co-Authored-By|Co-authored-by):\\s*.*(?:" +
      "noreply@anthropic\\.com|" +
      "claude(?:\\s|$)|" +
      "cursoragent@cursor\\.com|" +
      "@cursor\\.com|" +
      "ai@cursor\\.sh|" +
      "cursor@cursor\\.sh|" +
      "sos@cursor\\.sh|" +
      "copilot@github\\.com|" +
      "Copilot\\[bot\\]|" +
      "copilot-swe-agent\\[bot\\]|" +
      "codex@openai\\.com|" +
      "noreply@openai\\.com|" +
      "chatgpt-codex-connector\\[bot\\]|" +
      "aider@aider\\.chat|" +
      "amp@ampcode\\.com|" +
      "gemini@google\\.com|" +
      "gemini-code-assist@google\\.com|" +
      "gemini-cli-agent@google\\.com|" +
      "jules@google\\.com|" +
      "@codeium\\.com|" +
      "devin-ai-integration\\[bot\\]|" +
      "devin@cognition\\.ai|" +
      "devin@cognition-labs\\.com|" +
      "amazon-q-developer|" +
      "cline@cline\\.ai|" +
      "continue@continue\\.dev|" +
      "noreply@opencode\\.ai|" +
      "agent@warp\\.dev|" +
      "oz-agent@warp\\.dev|" +
      "jetbrains-ai\\[bot\\]|" +
      "\\+(?:Copilot(?:\\[bot\\])?|cursor\\[bot\\]|claude(?:\\[bot\\])?|" +
        "codex|gemini-code-assist(?:\\[bot\\])?|gemini-cli(?:\\[bot\\])?|" +
        "chatgpt-codex-connector\\[bot\\]|jetbrains-ai\\[bot\\]|" +
        "devin-ai-integration\\[bot\\]" +
      ")@users\\.noreply\\.github\\.com" +
    ")|" +
    "(?:Made-with|Made-With):\\s*Cursor\\b|" +
    "Amp-Thread-ID:" +
  ").*$",
  "im"
)

const BANNER_RE = new RegExp(
  "^[ \\t]*(?:#|//|--|/\\*|\\*|<!--)?[ \\t]*" +
    "(?:" +
      "(?:🤖\\s*)?Generated with (?:\\[)?(?:Claude Code|Cursor|opencode)|" +
      "Generated by Claude|" +
      "Made with Cursor|" +
      "Claude-Session:\\s*https?://" +
    ")" +
    ".*$",
  "im"
)

const isEmojiIsh = (ch: string): boolean => {
  if (ch.length === 0) {
    return false
  }
  const o = ch.codePointAt(0)
  if (o === undefined) {
    return false
  }
  return (
    (o >= 0x1f300 && o <= 0x1faff) ||
    (o >= 0x2600 && o <= 0x27bf) ||
    (o >= 0xfe00 && o <= 0xfe0f) ||
    o === 0x200d
  )
}

const splitKeepEnds = (text: string): Array<string> => {
  const lines = text.match(/[^\r\n]*(?:\r\n|\n|\r)?/g) ?? []
  if (lines.at(-1) === "") {
    lines.pop()
  }
  return lines
}

const stripInvisible = (text: string): { readonly text: string; readonly n: number } => {
  let count = 0
  const out: Array<string> = []
  const chars = [...text]
  for (let i = 0; i < chars.length; i++) {
    const ch = chars[i] ?? ""
    if (ch === "\u200d") {
      const prev = out.at(-1) ?? ""
      const nxt = chars[i + 1] ?? ""
      if (isEmojiIsh(prev) || isEmojiIsh(nxt)) {
        out.push(ch)
        continue
      }
    }
    if (ch === "\ufeff" && i === 0) {
      out.push(ch)
      continue
    }
    if (ZWSP_RE.test(ch) || BIDI_OVERRIDE_RE.test(ch) || TAG_RE.test(ch)) {
      count += 1
      continue
    }
    out.push(ch)
  }
  return { text: out.join(""), n: count }
}

const stripMatchingLines = (
  text: string,
  re: RegExp
): { readonly text: string; readonly n: number } => {
  const kept: Array<string> = []
  let n = 0
  for (const line of splitKeepEnds(text)) {
    if (re.test(line)) {
      n += 1
      continue
    }
    kept.push(line)
  }
  return { text: kept.join(""), n }
}

/** Strip deterministic Layer A marks. Keep emoji ZWJ and a leading BOM. */
export const applyLayerA = (text: string): LayerAResult => {
  const unicode = stripInvisible(text)
  const trailer = stripMatchingLines(unicode.text, AGENT_TRAILER_RE)
  const banner = stripMatchingLines(trailer.text, BANNER_RE)
  return {
    text: banner.text,
    removed: {
      unicode: unicode.n,
      trailer: trailer.n,
      banner: banner.n
    }
  }
}
